services:
  app:
    image: "ghcr.io/bilalshahdev/vynox-vpn-server:1.0.0"
    container_name: vynox_vpn_server
    ports:
      - "1110:1110"
    env_file:
      - ./.env.production
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('net').connect(process.env.PORT||1110).on('connect',()=>process.exit(0)).on('error',()=>process.exit(1))",
        ]
      interval: 10s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: vynox_vpn_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
